import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { BookOpen, Loader2, LockKeyhole, Send, Sparkles } from "lucide-react";
import { FormEvent, useState } from "react";
import { LoadingPage, PageIntro, ThemeToggle, usePlannerData } from "./PlannerShared";
import { trpc } from "@/lib/trpc";
import { Streamdown } from "streamdown";

export default function Coach() {
  const { data, profile, utils, isLoading } = usePlannerData();
  const [input, setInput] = useState("");
  const coach = trpc.coach.chat.useMutation({ onSuccess: () => { setInput(""); void utils.dashboard.get.invalidate(); } });
  if (isLoading || !data || !profile) return <LoadingPage />;
  const submit = (event: FormEvent) => { event.preventDefault(); if (input.trim()) coach.mutate({ message: input.trim() }); };
  return <div className="container max-w-[1050px] py-8 md:py-12"><div className="flex justify-end mb-3"><ThemeToggle /></div><PageIntro eyebrow="Coach / the next move" title="A little perspective, on demand." description="Not a glitter machine. Not a lecturer. Just a calm companion who helps you turn reflection into something you can try." /><div className="grid grid-cols-1 lg:grid-cols-[.72fr_1.28fr] gap-6"><Card className="border-0 bg-[#2b4b3b] text-[#f8f3e8] shadow-lg"><CardContent className="p-7"><Sparkles className="h-6 w-6 text-[#f3c56d]" /><h2 className="font-display text-4xl mt-5 leading-tight">Warm words.<br /><span className="text-[#f3c56d] italic">Useful next steps.</span></h2><p className="text-sm text-[#c0d1c2] mt-5 leading-relaxed">The coach can draw on ideas from habit-building and focused-work books, but it will not pretend to quote a book it has not verified.</p><div className="flex items-center gap-2 text-xs text-[#9db9a4] mt-8"><BookOpen className="h-4 w-4" /> Principles over performance</div><div className="flex items-center gap-2 text-xs text-[#9db9a4] mt-3"><LockKeyhole className="h-4 w-4" /> Private to your workspace</div></CardContent></Card><Card className="border-border/70 bg-card/80"><CardContent className="p-5 md:p-6"><div className="flex items-center justify-between border-b border-border/60 pb-4"><div><p className="font-semibold">YenePlan Coach</p><p className="text-xs text-muted-foreground mt-1">{profile.coachTone} mode</p></div><span className="h-2 w-2 rounded-full bg-[#61a66f]" /></div><div className="min-h-[360px] max-h-[500px] overflow-auto py-5 space-y-3">{data.coachMessages.length === 0 ? <div className="rounded-2xl bg-[#e8f0e6] p-4 text-sm text-[#4d6f56]">Start with the truth: “I keep postponing…” or ask for a tiny plan for something you want to improve.</div> : data.coachMessages.map((message: any) => <div key={message.id} className={`rounded-2xl p-4 text-sm leading-relaxed ${message.role === "assistant" ? "bg-[#e8f0e6] text-[#4d6f56] mr-8" : "bg-secondary text-foreground ml-8"}`}><Streamdown>{message.content}</Streamdown></div>)}</div><form onSubmit={submit} className="flex gap-2 border-t border-border/60 pt-4"><Input value={input} onChange={e => setInput(e.target.value)} placeholder="Help me make this smaller…" className="bg-background" /><Button type="submit" className="rounded-xl" disabled={!input.trim() || coach.isPending}>{coach.isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : <Send className="h-4 w-4" />}</Button></form></CardContent></Card></div></div>;
}
