import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { BatteryLow, CheckCheck, Loader2, Zap } from "lucide-react";
import { AddPlan, EmptyState, LoadingPage, PageIntro, PlanItem, usePlannerData } from "./PlannerShared";
import { trpc } from "@/lib/trpc";

export default function Today() {
  const { data, profile, utils, isLoading } = usePlannerData();
  const update = trpc.plan.status.useMutation({ onSuccess: () => void utils.dashboard.get.invalidate() });
  const remove = trpc.plan.delete.useMutation({ onSuccess: () => void utils.dashboard.get.invalidate() });
  const updateProfile = trpc.profile.update.useMutation({ onSuccess: () => void utils.dashboard.get.invalidate() });
  if (isLoading || !data || !profile) return <LoadingPage />;
  const todayPlans = data.plans.filter((plan: any) => plan.period === "day" && (plan.ethiopianDay === profile.currentDay || plan.ethiopianDay == null));
  const openPlans = todayPlans.filter((plan: any) => plan.status !== "done");
  const shownPlans = profile.energyMode === "low" ? openPlans.slice(0, 1) : profile.energyMode === "locked" ? openPlans.slice(0, 3) : todayPlans;
  return <div className="container max-w-[980px] py-8 md:py-12"><PageIntro eyebrow={`Today / ${profile.ethiopianYear}`} title="Keep the next promise." description="A short list, a clear pace, and enough room to be human." /><Card className="border-border/70 bg-card/80"><CardContent className="p-6 md:p-7"><div className="flex flex-col md:flex-row md:items-center gap-4 pb-5 border-b border-border/60"><div className="flex-1"><p className="text-xs uppercase tracking-[0.16em] text-primary font-semibold">Your pace today</p><p className="font-display text-2xl mt-1">{profile.energyMode === "low" ? "Minimum viable day" : profile.energyMode === "locked" ? "Focused sprint" : "Steady pace"}</p><p className="text-sm text-muted-foreground mt-1">{profile.energyMode === "low" ? "One kind action is enough. The rest is safe." : profile.energyMode === "locked" ? "Pick the top three and ignore the rest for now." : "A normal day is allowed to be normal."}</p></div><div className="flex gap-2"><Button variant={profile.energyMode === "low" ? "default" : "outline"} className="rounded-xl" onClick={() => updateProfile.mutate({ energyMode: profile.energyMode === "low" ? "normal" : "low" })}><BatteryLow className="h-4 w-4 mr-2" />{profile.energyMode === "low" ? "Reset pace" : "I’m overwhelmed"}</Button><Button variant={profile.energyMode === "locked" ? "default" : "outline"} className="rounded-xl" onClick={() => updateProfile.mutate({ energyMode: profile.energyMode === "locked" ? "normal" : "locked" })}><Zap className="h-4 w-4 mr-2" />Lock in</Button></div></div><div className="flex items-start justify-between mt-6"><div><p className="text-xs uppercase tracking-[0.18em] text-primary">Daily lane</p><h2 className="font-display text-3xl mt-2">{todayPlans.length ? `${todayPlans.filter((p: any) => p.status === "done").length} of ${todayPlans.length} complete` : "A blank page"}</h2></div><CheckCheck className="h-6 w-6 text-primary" /></div><div className="space-y-2 mt-6">{shownPlans.length ? shownPlans.map((plan: any) => <PlanItem key={plan.id} plan={plan} onStatus={status => update.mutate({ id: plan.id, status })} onDelete={() => remove.mutate({ id: plan.id })} />) : <EmptyState title="No promise has been added." text="Choose something small enough to finish even on a messy day." />}</div>{profile.energyMode === "low" && openPlans.length > 1 && <p className="rounded-2xl bg-accent p-4 text-sm text-accent-foreground mt-4"><strong>Anti-overwhelm mode:</strong> showing one move. Your other tasks are still safe.</p>}<AddPlan period="day" year={profile.ethiopianYear} month={profile.currentMonth} day={profile.currentDay} onAdded={() => void utils.dashboard.get.invalidate()} />{updateProfile.isPending && <p className="text-xs mt-3 text-muted-foreground flex items-center gap-2"><Loader2 className="h-3 w-3 animate-spin" /> Updating your pace…</p>}</CardContent></Card></div>;
}
